#!/usr/bin/env python3
"""FT master-spec archive tool (introduced v1.77.0).

The working spec (internal/scorecards/seed/master-spec.md) holds sections 1-12
(the current state) plus section 13: the ten newest changes in short form.
Everything older, and the full text of every change, lives append-only in
docs/spec-archive/:

    changelog-NN.md   full change-log entries, oldest first (grows at the end)
    history-NN.md     the old section-13 version table, frozen at v1.76.0
    INDEX.md          generated map: every version / pass -> its archive file

Commands
    check                      validate the working spec + archive (exit 1 on any problem)
    index                      regenerate docs/spec-archive/INDEX.md
    bump --version X.Y.Z --full FILE --short FILE [--reference-reviewed]
                               append FILE (the full entry) to the archive, put the short
                               block at the top of section 13, drop the oldest short block
                               beyond ten, refresh the version line / END marker, reindex.

Archive text is never edited: a correction goes in a new entry.
Run from anywhere; paths are relative to the repo root.
"""
import argparse
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SPEC = os.path.join(ROOT, "internal/scorecards/seed/master-spec.md")
ARCH = os.path.join(ROOT, "docs/spec-archive")

PART_LIMIT = 50_000   # raw characters per archive part (Claude's Drive read stops near 100k
                      # after Google Docs escaping; this leaves a wide margin)
RECENT_MAX = 10       # short entries kept in section 13
SHORT_MAX = 800       # characters per short entry
SPEC_MAX = 90_000     # working spec must stay readable in one Drive read
ESCAPE_MAX = 90_000   # estimated escaped length of any one file

END_SPEC = re.compile(r"^<!-- END FT-master-spec v(\d+\.\d+\.\d+) -->$")
END_PART = "<!-- END FT-spec-archive {kind}-{nn} -->"
ENTRY = re.compile(r"^> \*\*[A-Za-z ]*[Oo]verhaul:\*\* (\d{4}-\d\d-\d\d) \(([^)]*)\) — (.*)$")
SHORT = re.compile(r"^### v(\d+\.\d+\.\d+) · (\d{4}-\d\d-\d\d) · pass (\d+)(?: · (.+))?$")
ESCAPABLE = set("\\*_`#[]<>|!~{}")
# Entries whose text carries no version but whose pass the old section-13 table numbered.
# The archive text stays untouched; only the generated INDEX uses this.
VERSION_OVERRIDES = {("2026-05-30", "PM late evening, fourth pass"): "1.22.7"}  # EIGEN v1 ingest


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def write(p, s):
    with open(p, "w", encoding="utf-8", newline="\n") as f:
        f.write(s)


def escaped_len(s):
    return len(s) + sum(1 for c in s if c in ESCAPABLE)


def vtuple(v):
    try:
        return tuple(int(x) for x in v.split("."))
    except ValueError:
        return (-1,)


def parts(kind):
    out = []
    if os.path.isdir(ARCH):
        for n in sorted(os.listdir(ARCH)):
            m = re.fullmatch(kind + r"-(\d\d)\.md", n)
            if m:
                out.append((int(m.group(1)), n))
    return out


# ---------------------------------------------------------------- parsing

def title_of(body, limit=110):
    b = re.match(r"\*\*(.+?)\*\*", body)
    t = re.sub(r"\s+", " ", b.group(1) if b else body).strip(" .").replace("|", "/")
    if len(t) > limit:  # cut on a word boundary, not mid-word
        t = t[:limit].rsplit(" ", 1)[0].rstrip(" ,;:-—+(") + "…"
    return t


def version_of(text):
    m = re.search(r"\(v(\d+\.\d+(?:\.\d+)?)", text[:400]) or re.search(r"\bv(\d+\.\d+\.\d+)", text[:400])
    return m.group(1) if m else "—"


def scs(text):
    return ", ".join(sorted(set(re.findall(r"SC-\d+(?:\.\d+)?", text)), key=lambda s: [int(x) for x in re.findall(r"\d+", s)]))


def archive_entries():
    """[(file, date, pass_label, version, sc, title)] oldest first."""
    out = []
    for _, name in parts("changelog"):
        for line in read(os.path.join(ARCH, name)).split("\n"):
            m = ENTRY.match(line)
            if m:
                title = title_of(m.group(3))
                v = version_of(line)
                if v == "—":
                    v = VERSION_OVERRIDES.get((m.group(1), m.group(2)), v)
                out.append((name, m.group(1), m.group(2), v, scs(title), title))
    return out


def archive_rows():
    out = []
    for _, name in parts("history"):
        for line in read(os.path.join(ARCH, name)).split("\n"):
            m = re.match(r"^\| ([^|]+?) \| ([^|]+?) \| (.*) \|$", line)
            if m and m.group(1) not in ("Version",) and not set(m.group(1)) <= set("-"):
                title = title_of(m.group(3))
                out.append((name, m.group(1), m.group(2), scs(title), title))
    return out


def build_index():
    ents, rows = archive_entries(), archive_rows()
    o = ["# FT spec archive — index", "",
         "Generated by `tools/spec_archive.py index` — do not edit by hand. Maps every version and pass of the FT "
         "master spec's history to the archive file that holds its full text. `changelog-NN.md` parts are append-only "
         "and oldest-first; `history-NN.md` parts are the old section-13 table, frozen at v1.76.0 (for versions from "
         "about 1.37 it restates the change-log entry in shorter form). Text in the parts is never edited; a "
         "correction is a new entry. The ten newest changes are also in section 13 of the working spec. **A version may "
         "appear in only one of the two tables below — look it up in both.**", "",
         f"## Change-log entries — {len(ents)}, newest first", "",
         "| Date | Pass | Version | SC | Title | File |", "|---|---|---|---|---|---|"]
    for f, d, p, v, sc, t in reversed(ents):
        o.append(f"| {d} | {p} | {v} | {sc or '—'} | {t} | {f} |")
    o += ["", f"## Old section-13 version table — {len(rows)} rows, newest version first", "",
          "| Version | Date | SC | Title | File |", "|---|---|---|---|---|"]
    for f, v, d, sc, t in sorted(rows, key=lambda r: vtuple(r[1]), reverse=True):
        o.append(f"| {v} | {d} | {sc or '—'} | {t} | {f} |")
    o += ["", "<!-- END FT-spec-archive INDEX -->", ""]
    return "\n".join(o)


def split_spec(text):
    """-> (before_13, recent_blocks[list of str], after_blocks) around section 13."""
    i = text.index("\n## 13.")
    head, tail = text[: i + 1], text[i + 1:]
    first = tail.index("### v") if "### v" in tail else None
    return head, tail, first


def recent_blocks(text):
    _, tail, first = split_spec(text)
    if first is None:
        return []
    end = tail.index("\n---\n", first)
    body = tail[first:end]
    blocks = [b.strip("\n") for b in re.split(r"\n(?=### v)", body)]
    return [b for b in blocks if b]


# ---------------------------------------------------------------- check

def check():
    errs = []
    spec = read(SPEC)
    lines = [l for l in spec.rstrip("\n").split("\n")]
    m = END_SPEC.match(lines[-1]) if lines else None
    if not m:
        errs.append("working spec: last line is not `<!-- END FT-master-spec vX.Y.Z -->`")
        end_v = None
    else:
        end_v = m.group(1)
    cur = re.search(r"\*\*Current version: v(\d+\.\d+\.\d+) · (\d{4}-\d\d-\d\d)\*\*", spec)
    ref = re.search(r"<!-- reference_reviewed: v(\d+\.\d+\.\d+) (\d{4}-\d\d-\d\d) -->", spec)
    if not cur:
        errs.append("working spec: missing `**Current version: vX · DATE**` line")
    if end_v and cur and cur.group(1) != end_v:
        errs.append(f"working spec: END marker v{end_v} != current version v{cur.group(1)}")
    if not ref:
        errs.append("working spec: missing `reference_reviewed` marker")
    elif cur and ref.group(1) != cur.group(1):
        errs.append(f"working spec: reference_reviewed v{ref.group(1)} is behind current version v{cur.group(1)} "
                    "(update the affected sections 1-12, then set the marker)")
    if len(spec) > SPEC_MAX:
        errs.append(f"working spec is {len(spec):,} chars (max {SPEC_MAX:,}): archive more")
    if escaped_len(spec) > ESCAPE_MAX:
        errs.append(f"working spec escapes to ~{escaped_len(spec):,} chars (max {ESCAPE_MAX:,})")
    if "\n## 13." not in spec:
        errs.append("working spec: missing section 13")
        return errs

    blocks = recent_blocks(spec)
    if not blocks:
        errs.append("section 13: no `### vX.Y.Z · DATE · pass N` entries")
    if len(blocks) > RECENT_MAX:
        errs.append(f"section 13: {len(blocks)} entries (max {RECENT_MAX})")
    vers = []
    for b in blocks:
        h = SHORT.match(b.split("\n")[0])
        if not h:
            errs.append(f"section 13: bad entry heading: {b.split(chr(10))[0][:60]}")
            continue
        vers.append(h.group(1))
        if len(b) > SHORT_MAX:
            errs.append(f"section 13: v{h.group(1)} entry is {len(b)} chars (max {SHORT_MAX})")
        if "Supersedes" not in b:
            errs.append(f"section 13: v{h.group(1)} entry has no 'Supersedes' pointer")
    if vers != sorted(vers, key=vtuple, reverse=True):
        errs.append("section 13: entries are not newest-first")
    if cur and vers and vers[0] != cur.group(1):
        errs.append(f"section 13: newest entry v{vers[0]} != current version v{cur.group(1)}")

    # archive
    idx_versions = {e[3] for e in archive_entries()} | {r[1] for r in archive_rows()}
    for v in vers:
        if v not in idx_versions:
            errs.append(f"v{v} is in section 13 but its full entry is not in the archive")
    for b in blocks:
        for sv in re.findall(r"Supersedes v(\d+\.\d+(?:\.\d+)?)", b):
            if sv not in idx_versions and sv not in vers:
                errs.append(f"'Supersedes v{sv}' does not resolve (not in section 13 or the archive index)")
    for kind in ("changelog", "history"):
        ps = parts(kind)
        if not ps:
            errs.append(f"archive: no {kind} parts")
        if [n for n, _ in ps] != list(range(1, len(ps) + 1)):
            errs.append(f"archive: {kind} part numbers are not 01..{len(ps):02d}")
        for n, name in ps:
            t = read(os.path.join(ARCH, name))
            if not t.rstrip("\n").endswith(END_PART.format(kind=kind, nn=f"{n:02d}")):
                errs.append(f"archive: {name} does not end with its END marker")
            if len(t) > PART_LIMIT + 7000 and kind == "changelog" and n < len(ps):
                errs.append(f"archive: {name} is {len(t):,} chars (limit ~{PART_LIMIT:,} + one entry)")
            if escaped_len(t) > ESCAPE_MAX:
                errs.append(f"archive: {name} escapes to ~{escaped_len(t):,} chars (max {ESCAPE_MAX:,})")
    ip = os.path.join(ARCH, "INDEX.md")
    if not os.path.exists(ip) or read(ip) != build_index():
        errs.append("archive: INDEX.md is missing or out of date — run `tools/spec_archive.py index`")
    elif escaped_len(read(ip)) > ESCAPE_MAX:
        errs.append("archive: INDEX.md is too long for one read")
    return errs


# ---------------------------------------------------------------- bump

def bump(version, full_path, short_path, reference_reviewed):
    full = read(full_path).strip("\n")
    short = read(short_path).strip("\n")
    if "\n" in full or not ENTRY.match(full):
        sys.exit("--full must be ONE line in the entry form: > **Overhaul:** YYYY-MM-DD (Nth pass) — **Title (vX.Y.Z).** …")
    h = SHORT.match(short.split("\n")[0])
    if not h or h.group(1) != version:
        sys.exit(f"--short must start with `### v{version} · YYYY-MM-DD · pass N · SC-…`")
    if len(short) > SHORT_MAX:
        sys.exit(f"short entry is {len(short)} chars (max {SHORT_MAX})")
    if f"v{version}" not in full[:400]:
        sys.exit(f"--full title should carry (v{version})")
    date = h.group(2)

    # 1. archive: append to the last changelog part, or open a new one
    ps = parts("changelog")
    n, name = ps[-1]
    path = os.path.join(ARCH, name)
    t = read(path).rstrip("\n")
    marker = END_PART.format(kind="changelog", nn=f"{n:02d}")
    assert t.endswith(marker)
    body = t[: -len(marker)].rstrip("\n")
    if len(body) + len(full) + 4 > PART_LIMIT:
        write(path, t + "\n")
        n += 1
        name = f"changelog-{n:02d}.md"
        path = os.path.join(ARCH, name)
        body = (f"# FT spec archive — change log, part {n:02d}\n\nFull, unedited change-log entries of the FT "
                "master spec, oldest first (this file only ever grows at the end; existing text is never edited — "
                "a correction goes in a new entry). Map of every version and pass to its file: INDEX.md.\n")
        marker = END_PART.format(kind="changelog", nn=f"{n:02d}")
    write(path, body + "\n>\n" + full + "\n\n" + marker + "\n")

    # 2. working spec: current-version line, section 13, END marker
    spec = read(SPEC)
    spec = re.sub(r"\*\*Current version: v[\d.]+ · [\d-]+\*\*[^\n]*",
                  lambda m: f"**Current version: v{version} · {date}** — latest change: "
                            + re.sub(r"\s+", " ", re.match(r"\*\*(.+?)\*\*", short.split("\n", 2)[2].strip()).group(1)).rstrip(".")
                            + " (§13).", spec, count=1)
    head, tail, first = split_spec(spec)
    end = tail.index("\n---\n", first)
    old = [b for b in re.split(r"\n(?=### v)", tail[first:end].strip("\n")) if b]
    blocks = [short] + old
    blocks = blocks[:RECENT_MAX]
    tail = tail[:first] + "\n\n".join(blocks) + "\n" + tail[end:]
    spec = head + tail
    spec = re.sub(r"<!-- END FT-master-spec v[\d.]+ -->", f"<!-- END FT-master-spec v{version} -->", spec)
    if reference_reviewed:
        spec = re.sub(r"<!-- reference_reviewed: [^>]+ -->", f"<!-- reference_reviewed: v{version} {date} -->", spec)
    write(SPEC, spec)
    write(os.path.join(ARCH, "INDEX.md"), build_index())
    print(f"v{version}: full entry appended to {name}; section 13 now has {len(blocks)} entries")
    if not reference_reviewed:
        print("NOTE: reference_reviewed was NOT updated — `check` will fail until the affected sections 1-12 are "
              "revised and the marker is set (re-run bump with --reference-reviewed, or edit the marker).")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("check")
    sub.add_parser("index")
    b = sub.add_parser("bump")
    b.add_argument("--version", required=True)
    b.add_argument("--full", required=True)
    b.add_argument("--short", required=True)
    b.add_argument("--reference-reviewed", action="store_true")
    a = ap.parse_args()
    if a.cmd == "index":
        write(os.path.join(ARCH, "INDEX.md"), build_index())
        print("INDEX.md written")
    elif a.cmd == "bump":
        bump(a.version, a.full, a.short, a.reference_reviewed)
        errs = check()
        for e in errs:
            print("CHECK:", e)
        sys.exit(1 if errs else 0)
    else:
        errs = check()
        for e in errs:
            print("FAIL:", e)
        print("spec archive: OK" if not errs else f"{len(errs)} problem(s)")
        sys.exit(1 if errs else 0)


if __name__ == "__main__":
    main()
